services:
    rxu.registeredfor.listener:
        class: rxu\registeredfor\event\main_listener
        arguments:
            - '@language'
            - '@request'
            - '@template'
        tags:
            - { name: event.listener }
